sudo: false
language: node_js
node_js:
- '0.12'
- '0.10'
- iojs
after_success: npm run coverage
env:
- secure: "B8/6b4bkaIVWd1e9SYFRGFCUpXowXSB6bMLU27a3U6+9WKGQzAoIxTVtbrvTsrx3ktx20L+usKfx0BssZcY8AlRt/lBKc2pSUgsXlfvwbf6I/1dMZBdkvHPL5OyyTe5qUWtStG92AIRlKD5qFSCuBxkCOlUSZun0/Co3NiLbisrYfi4oF/DDXUU4dv9jbWmS/pfU+Djyn0eqQB10djG+5xtZ0CnRGTk7VgjNSZkeCN25NhFWVSGc9c6wvK9/xhlXI5mwSyG9r78Oci3/0c64tIKnfVsF5rnBuFQmKPlKoXcLy+62oUhY/2jVE/u9CHUBluHbSgkR/PmMEezT7lST2wMbwhtbrVsu7jNCWNgUQuaVEfhQ5xMyPn5hQ+4U18AmIBNTBLG4ELkHTcsBoXDYy+5BstdkXz70GYZocI3UbSjExMscqwBKzKyl5Cb5rh58OaRZ+gicQhGtt66OkCG184nIJEmHUA1DfcOg7EWEsGxWtgS5drAsd7xUHOCDfbnCmY2vVu+QiPusQm5ISDl0HZo3mpPqjI9zM3WLfIZTTJ2PVqEfx3YE3Th44oVJYFwN7kKxcXJQiJvsyUbQ/JsE3T5cZAzjgQ01uqZvFas/QVYSWCh3yxpmJRFVhVaGVoH67TJo1jKV/N1BT7xf3Hy7aEtwjMTcUrgMrcg8PdMLEL8="
